name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Deploy en EC2 (real)
        run: |
          aws ssm send-command \
            --instance-ids i-0fe74284ac518b019 \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy actualizado" \
            --parameters commands='[
              "cd /home/ubuntu",
              "if [ ! -d mi-repositorio-devops ]; then git clone https://github.com/katerine27-jpg/mi-repositorio-devops.git; fi",
              "cd mi-repositorio-devops",
              "git pull origin main || git pull origin master",
              "cd app",
              "sudo docker rm -f mi-flask-app || true",
              "sudo docker build -t mi-flask-app .",
              "sudo docker run -d -p 5000:5000 --name mi-flask-app mi-flask-app"
            ]' \
            --region us-east-1
