name: Deploy to S3 and EC2

on:
  push:
    branches:
      - main
      - master

jobs:
  build-upload-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip project
        run: zip -r mi-app.zip app docker-compose.yml

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 cp mi-app.zip s3://mi-pipeline-source-113835246898/mi-app.zip

      - name: Deploy on EC2 with SSM
        run: |
          aws ssm send-command \
            --instance-ids i-0fe74284ac518b019 \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy app from GitHub Actions" \
            --parameters commands='[
              "cd /home/ubuntu",
              "rm -rf mi-app",
              "mkdir -p mi-app/app",
              "echo \"from flask import Flask\" > mi-app/app/app.py",
              "echo \"app = Flask(__name__)\" >> mi-app/app/app.py",
              "echo \"\" >> mi-app/app/app.py",
              "echo \"@app.route(\\\"/\\\")\" >> mi-app/app/app.py",
              "echo \"def home():\" >> mi-app/app/app.py",
              "echo \"    return \\\"<h1>Actualizado automáticamente 🚀</h1>\\\"\" >> mi-app/app/app.py",
              "echo \"\" >> mi-app/app/app.py",
              "echo \"if __name__ == \\\"__main__\\\":\" >> mi-app/app/app.py",
              "echo \"    app.run(host=\\\"0.0.0.0\\\", port=5000)\" >> mi-app/app/app.py",
              "echo \"flask==2.3.2\" > mi-app/app/requirements.txt",
              "echo \"FROM python:3.11-slim\" > mi-app/app/Dockerfile",
              "echo \"WORKDIR /app\" >> mi-app/app/Dockerfile",
              "echo \"COPY requirements.txt .\" >> mi-app/app/Dockerfile",
              "echo \"RUN pip install -r requirements.txt\" >> mi-app/app/Dockerfile",
              "echo \"COPY . .\" >> mi-app/app/Dockerfile",
              "echo \"EXPOSE 5000\" >> mi-app/app/Dockerfile",
              "echo \"CMD [\\\"python\\\", \\\"app.py\\\"]\" >> mi-app/app/Dockerfile",
              "sudo systemctl start docker",
              "sudo docker rm -f mi-flask-app || true",
              "cd /home/ubuntu/mi-app/app",
              "sudo docker build -t mi-flask-app .",
              "sudo docker run -d -p 5000:5000 --name mi-flask-app mi-flask-app"
            ]' \
            --region us-east-1
